name: Deploy EC2 Instance

on:
  workflow_dispatch:
    inputs:
      instance_type:
        description: 'EC2 Instance Type'
        default: 't2.micro'
        required: true
      ami_id:
        description: 'Amazon Machine Image (AMI) ID'
        default: 'ami-0c55b159cbfafe1f0'
        required: true
