name: Terminate EC2 Instances

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  terminate-instances:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Terminate EC2 instance
      run: |
        INSTANCE_ID="ami-0522ab6e1ddcc7055"  # Replace with your instance ID
        aws ec2 terminate-instances --instance-ids $INSTANCE_ID
        aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID
